@LeaveManagementBackend_HostAddress = https://localhost:7209


###

POST {{LeaveManagementBackend_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "dhruv@tx.com",
  "password": "Dhruv123"
}

###

GET {{LeaveManagementBackend_HostAddress}}/api/leaves/my
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJyYWphdEB0eC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJFbXBsb3llZSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJSYWphdCBFbXAiLCJleHAiOjE3ODE0MTYwNzAsImlzcyI6IkxlYXZlTWFuYWdlbWVudEJhY2tlbmQiLCJhdWQiOiJMZWF2ZU1hbmFnZW1lbnRVc2VycyJ9.QkV6OdvfdU_dXDgneQNxXwSODEZDwhKpiJmptFhcT0I
###

POST {{LeaveManagementBackend_HostAddress}}/api/leaves
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjIiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJkaHJ1dkB0eC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJNYW5hZ2VyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6IkRocnV2IE1hbmFnZXIiLCJleHAiOjE3ODE0MjU2ODgsImlzcyI6IkxlYXZlTWFuYWdlbWVudEJhY2tlbmQiLCJhdWQiOiJMZWF2ZU1hbmFnZW1lbnRVc2VycyJ9.BnrioN6iZH3P6D2N0x9QnwkFOMdXK8_Dq7zSNMSl0Vw
Content-Type: application/json

{
  "leaveTypeId": 1,
  "startDate": "2026-06-25",
  "endDate": "2026-06-30",
  "reason": "Family Function"
}

###

@id=2
PUT {{LeaveManagementBackend_HostAddress}}/api/leaves/{{id}}/cancel
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJyYWphdEB0eC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJFbXBsb3llZSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJSYWphdCBFbXAiLCJleHAiOjE3ODE0MTYwNzAsImlzcyI6IkxlYXZlTWFuYWdlbWVudEJhY2tlbmQiLCJhdWQiOiJMZWF2ZU1hbmFnZW1lbnRVc2VycyJ9.QkV6OdvfdU_dXDgneQNxXwSODEZDwhKpiJmptFhcT0I
###

GET {{LeaveManagementBackend_HostAddress}}/api/leaves/repotees
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjIiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJkaHJ1dkB0eC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJNYW5hZ2VyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6IkRocnV2IE1hbmFnZXIiLCJleHAiOjE3ODE0MjYzNjgsImlzcyI6IkxlYXZlTWFuYWdlbWVudEJhY2tlbmQiLCJhdWQiOiJMZWF2ZU1hbmFnZW1lbnRVc2VycyJ9.fgRQy39eo0a1BeEc0EgPDVpC9BnGq75codOTZz8InCg


PUT {{LeaveManagementBackend_HostAddress}}/api/leaves/{{id}}/approve
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjIiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJkaHJ1dkB0eC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJNYW5hZ2VyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6IkRocnV2IE1hbmFnZXIiLCJleHAiOjE3ODE0MjU2ODgsImlzcyI6IkxlYXZlTWFuYWdlbWVudEJhY2tlbmQiLCJhdWQiOiJMZWF2ZU1hbmFnZW1lbnRVc2VycyJ9.BnrioN6iZH3P6D2N0x9QnwkFOMdXK8_Dq7zSNMSl0Vw
###

@id=2
PUT {{LeaveManagementBackend_HostAddress}}/api/leaves/{{id}}/approve
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjIiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJkaHJ1dkB0eC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJNYW5hZ2VyIiwiaHR0cDovL3NjaGVtYXMueG1sc29hcC5vcmcvd3MvMjAwNS8wNS9pZGVudGl0eS9jbGFpbXMvbmFtZSI6IkRocnV2IE1hbmFnZXIiLCJleHAiOjE3ODE0MjYzNjgsImlzcyI6IkxlYXZlTWFuYWdlbWVudEJhY2tlbmQiLCJhdWQiOiJMZWF2ZU1hbmFnZW1lbnRVc2VycyJ9.fgRQy39eo0a1BeEc0EgPDVpC9BnGq75codOTZz8InCg
###

