@LeaveManagementBackend_HostAddress = https://localhost:7209
@token=
###
POST {{LeaveManagementBackend_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "Dhruv@tx.com",
  "password": "Dhruv123"
}

###

GET {{LeaveManagementBackend_HostAddress}}/api/leaves/my
Authorization: Bearer {{token}}
###

POST {{LeaveManagementBackend_HostAddress}}/api/leaves
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "leaveTypeId": 1,
  "startDate": "2026-07-02",
  "endDate": "2026-07-05",
  "reason": "checkup"
}

###

@id=2
PUT {{LeaveManagementBackend_HostAddress}}/api/leaves/{{id}}/cancel
Authorization: Bearer {{token}}
###

GET {{LeaveManagementBackend_HostAddress}}/api/leaves/repotees
Authorization: Bearer {{token}}
###

@id=1
PUT {{LeaveManagementBackend_HostAddress}}/api/leaves/{{id}}/approve
Authorization: Bearer {{token}}


###

GET {{LeaveManagementBackend_HostAddress}}/api/admin/employees
Authorization: Bearer {{token}}
###

@month=7
@year=2026
GET {{LeaveManagementBackend_HostAddress}}/api/admin/reports/summary?month={{month}}&year={{year}}
Authorization: Bearer {{token}}
###

@id=2
PUT {{LeaveManagementBackend_HostAddress}}/api/leaves/{{id}}/reject
Authorization: Bearer {{token}}
###
