@LeaveManagementBackend_HostAddress = https://localhost:7209

GET {{LeaveManagementBackend_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{LeaveManagementBackend_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "rajat@tx.com",
  "password": "Rajat123"
}

###

GET {{LeaveManagementBackend_HostAddress}}/api/leaves/my
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjMiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJyYWphdEB0eC5jb20iLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJFbXBsb3llZSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJSYWphdCBFbXAiLCJleHAiOjE3ODE0MTA3MzEsImlzcyI6IkxlYXZlTWFuYWdlbWVudEJhY2tlbmQiLCJhdWQiOiJMZWF2ZU1hbmFnZW1lbnRVc2VycyJ9.XqxCqxcsuX9uqtd8azM6PGcXNY7JGSyiH6uF-v-h2lM 
###
