// <auto-generated />
using System;
using LeaveManagementBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LeaveManagementBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260615184434_addedLeaveBalance-seedEmp")]
    partial class addedLeaveBalanceseedEmp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("LeaveManagementBackend.Models.LeaveBalance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BalanceDays")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LeaveTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("LeaveBalances");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BalanceDays = 20m,
                            LeaveTypeId = 1,
                            UserId = 3,
                            Year = 2026
                        },
                        new
                        {
                            Id = 2,
                            BalanceDays = 10m,
                            LeaveTypeId = 2,
                            UserId = 3,
                            Year = 2026
                        },
                        new
                        {
                            Id = 3,
                            BalanceDays = 15m,
                            LeaveTypeId = 3,
                            UserId = 3,
                            Year = 2026
                        },
                        new
                        {
                            Id = 4,
                            BalanceDays = 20m,
                            LeaveTypeId = 1,
                            UserId = 2,
                            Year = 2026
                        },
                        new
                        {
                            Id = 5,
                            BalanceDays = 10m,
                            LeaveTypeId = 2,
                            UserId = 2,
                            Year = 2026
                        },
                        new
                        {
                            Id = 6,
                            BalanceDays = 15m,
                            LeaveTypeId = 3,
                            UserId = 2,
                            Year = 2026
                        },
                        new
                        {
                            Id = 7,
                            BalanceDays = 20m,
                            LeaveTypeId = 1,
                            UserId = 4,
                            Year = 2026
                        },
                        new
                        {
                            Id = 8,
                            BalanceDays = 10m,
                            LeaveTypeId = 2,
                            UserId = 4,
                            Year = 2026
                        },
                        new
                        {
                            Id = 9,
                            BalanceDays = 15m,
                            LeaveTypeId = 3,
                            UserId = 4,
                            Year = 2026
                        },
                        new
                        {
                            Id = 10,
                            BalanceDays = 20m,
                            LeaveTypeId = 1,
                            UserId = 5,
                            Year = 2026
                        },
                        new
                        {
                            Id = 11,
                            BalanceDays = 10m,
                            LeaveTypeId = 2,
                            UserId = 5,
                            Year = 2026
                        },
                        new
                        {
                            Id = 12,
                            BalanceDays = 15m,
                            LeaveTypeId = 3,
                            UserId = 5,
                            Year = 2026
                        },
                        new
                        {
                            Id = 13,
                            BalanceDays = 20m,
                            LeaveTypeId = 1,
                            UserId = 6,
                            Year = 2026
                        },
                        new
                        {
                            Id = 14,
                            BalanceDays = 10m,
                            LeaveTypeId = 2,
                            UserId = 6,
                            Year = 2026
                        },
                        new
                        {
                            Id = 15,
                            BalanceDays = 15m,
                            LeaveTypeId = 3,
                            UserId = 6,
                            Year = 2026
                        });
                });

            modelBuilder.Entity("LeaveManagementBackend.Models.LeaveRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LeaveTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LeaveTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("LeaveRequests");
                });

            modelBuilder.Entity("LeaveManagementBackend.Models.LeaveType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("LeaveTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Annual Leave"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Unpaid Leave"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sick Leave"
                        });
                });

            modelBuilder.Entity("LeaveManagementBackend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("ManagerId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("ManagerId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@tx.com",
                            FirstName = "Prajwal",
                            LastName = "Admin",
                            PasswordHash = "$2a$11$SFpxXxGU5fvbEplsiJHDBOXB1oBXK4AszGlq/NYgNssdax35QKScm",
                            Role = 10,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "dhruv@tx.com",
                            FirstName = "Dhruv",
                            LastName = "Manager",
                            PasswordHash = "$2a$11$KlyHJ58LYt64WwHmIJpc4uiZI1WjdJnlPuZY6tG3iM7JvfAdvXqVq",
                            Role = 11,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rajat@tx.com",
                            FirstName = "Rajat",
                            LastName = "Emp",
                            ManagerId = 2,
                            PasswordHash = "$2a$11$zxd3qBptSGxmYSYxWAX12ezaF6U0NFhQUh04yzqKoFLZ7EBa/Xk4a",
                            Role = 12,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jasneet@tx.com",
                            FirstName = "Jasneet",
                            LastName = "Emp",
                            ManagerId = 2,
                            PasswordHash = "$2a$11$LUn4hYzS/8KdNoO9/bgJZOaYIT6NNBYz4gmmbMXKN0vJDVZw3YreC",
                            Role = 12,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "raghav@tx.com",
                            FirstName = "Raghav",
                            LastName = "Emp",
                            ManagerId = 2,
                            PasswordHash = "$2a$11$jm.xcSXsIYMyEl02IwuhE.1/yOcTmEkriLZciVfTzQgrg7j6D2vnW",
                            Role = 12,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hardil@tx.com",
                            FirstName = "Hardil",
                            LastName = "Emp",
                            ManagerId = 2,
                            PasswordHash = "$2a$11$20Lh2SMf2TOGRYzUWL6HDOOw0kj/ymH1YqLdm8RxB8FBP27sCTCsK",
                            Role = 12,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("LeaveManagementBackend.Models.LeaveBalance", b =>
                {
                    b.HasOne("LeaveManagementBackend.Models.LeaveType", "LeaveType")
                        .WithMany("LeaveBalance")
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeaveManagementBackend.Models.User", "User")
                        .WithMany("LeaveBalance")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeaveType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LeaveManagementBackend.Models.LeaveRequest", b =>
                {
                    b.HasOne("LeaveManagementBackend.Models.LeaveType", "LeaveType")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("LeaveTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LeaveManagementBackend.Models.User", "User")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LeaveType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LeaveManagementBackend.Models.User", b =>
                {
                    b.HasOne("LeaveManagementBackend.Models.User", "Manager")
                        .WithMany("Reportees")
                        .HasForeignKey("ManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Manager");
                });

            modelBuilder.Entity("LeaveManagementBackend.Models.LeaveType", b =>
                {
                    b.Navigation("LeaveBalance");

                    b.Navigation("LeaveRequests");
                });

            modelBuilder.Entity("LeaveManagementBackend.Models.User", b =>
                {
                    b.Navigation("LeaveBalance");

                    b.Navigation("LeaveRequests");

                    b.Navigation("Reportees");
                });
#pragma warning restore 612, 618
        }
    }
}
